### ISSUE TITLE
Hibás állapot

### ISSUE THREAD

**Issue by sonycim** [laszlojakab/homeassistant-dijnet#10]
Tisztelt Uram!

Az integráció beállítása után azt vettem észre, hogy az egyik szolgáltatónál nyitott tételt jelez.
Pedig az a számla már rég befizetésre került.
Ellenőriztem a dijnet felületén, és ott sincs nyitott tételem.
Szükség van esetleg még valamilyen plusz információra?

/BL

**Comment by laszlojakab** [comment]
Kedves BL,

Lenne néhány kérdésem: 
- 3 óránként frissülnek az adatok, régebben történt meg a fizetés?
- újra lett már indítva a HA mióta befizetés megtörtént?
- a Dijnet oldalára bejelentkezve mi látható az adott tétel sorában? Megjelenik a tétel bejelentkezés után a  https://www.dijnet.hu/ekonto/control/main oldalon?

**Comment by sonycim** [comment]
Az integráció bőven (hetekkel) a befizetés után lett telepítve.
Tehát az első két kérdésre igen a válaszom.
A harmadikra pedig "nem" - nem volt befizetendő számlám.
Időközben már a helyes, 0Ft érték szerepel a befizetendő összegnél - az integrációban is.

**Comment by laszlojakab** [comment]
Ami valószínűleg történt, hogy a befizetés megtörtént, de a szolgáltató még nem tekintette rendezettnek a számlát. A jelenleg kiadott integrációban azt figyeli, hogy a szolgáltató visszajelzett-e, hogy rendezett a számla, nem pedig azt, hogy sikeres volt-e a fizetés (ez hamarosan változni fog egy nem sokára elkészülő verzióban). Esetleg meg lehetne nézni, hogy az számlához tartozó előzmények fülön nem-e az történt, hogy megtörtént a fizetés, majd a szolgáltató, csak sokkal később jelezte azt vissza.

**Comment by sonycim** [comment]
Nem látom, hogy a szolgáltató visszajelezte volna a teljesítést.
Nem is igazán akarok rugózni ezen a kérdésem, hiszen most remekül működik.
Bár azóta számlám nem érkezett, így befizetésem sem volt. .)
Illetve, ha későbbi verzióban amúgy is lesznek változások, akkor talán nem is érdemes időt szánni erre.
![dijnet_integracio](https://user-images.githubusercontent.com/72749518/147420179-159c935b-64b5-4f7f-9fe9-f757952f098f.jpg)

**Comment by laszlojakab** [comment]
Rendben, akkor lezárom a tételt, ha később mégis előfordulna, akkor nyugodtan nyiss egy újat.
