### ISSUE TITLE
"Dijnet" download directory location

### ISSUE THREAD

**Issue by KixMan28** [laszlojakab/homeassistant-dijnet#2]
Where I need to create the Dijnet download_dir?

**Comment by laszlojakab** [comment]
Integration automatically creates it in _config_ shared directory: 
/usr/share/hassio/homeassistant/<download_dir>

**Comment by spider7611** [comment]
Akkor hol van ha dockerben futtatom a HA-t?

**Comment by KixMan28** [comment]
Köszönöm szépen. Telepítettem a komponenst és hozzáadtam a configuration.yaml-hez a megfelelő utasításokat. Újraindulás után megjelent két új szenzor (nekem csak egy szolgáltató van a dijnetben): egy szenzor a szolgáltatóra és egy szenzor az összesített számlaösszegre. Helyesen mutatta az adatokat. Utána aktiváltam a download_dir sort a configuration.yaml-ben. Újraindítás után, létrehozta a Dijnet mappát és letöltötte a PDF és XML számlát, de közben elérhetetlené vált a szolgáltató szenzor. Az összesített számlaösszeg szenzor továbbra is működik. Mi lehet a gond?
Kommenteltem a download_dir utasítást a configuration.yaml-ben de nem oldotta meg a problémát. Továbbra sem érhető el a szolgáltató szenzor.

**Comment by laszlojakab** [comment]
@spider7611 sima szenzorként add hozzá, ne binary_sensor-ként

**Comment by laszlojakab** [comment]
@KixMan28 #1 issue-ban találsz erről infót: 

https://github.com/laszlojakab/homeassistant-dijnet/issues/1#issuecomment-634470064

**Comment by KixMan28** [comment]
@laszlojakab Köszi szépen. Leírom, hogy mit értek eddig a működéséből: 
1) új telepítésnél a szolgáltató szenzor "nem elérhető" legalább 3 óráig vagy az első számláig?
2) 3 óra után vagy csak az első számla után változik elérhetővé? Ha már 3 óra után elérhető de nincs számla, akkor mit mutat?
3) ha van új számla aktivá válik a szolgáltató szenzor, de azonnal le is tölti a számlát és újból "nem elérhetővé válik?

Javaslat:  a szolgáltató szenzor legyen mindig aktív, ha van számla és nincs befizetve akkor a számla összegét mutassa, ha nincs számla, vagy már befizetésre került, akkor mutasson 0 Ft-ot

**Comment by KixMan28** [comment]
@laszlojakab  Úgy tünik letelt a 3 óra, most újból látszik a szilgáltató szenzor.

Esetleg egy másik javaslat: legyen állítható a frissítési intervallum.

Egyébként nagyon szépen köszönöm az alkalmazást.

**Comment by laszlojakab** [comment]
@KixMan28 

> @laszlojakab Úgy tünik letelt a 3 óra, most újból látszik a szilgáltató szenzor.
> 
> Esetleg egy másik javaslat: legyen állítható a frissítési intervallum.
> 
> Egyébként nagyon szépen köszönöm az alkalmazást.

Egyelőre működik a scan_interval lehetőség:
https://www.home-assistant.io/docs/configuration/platform_options/#scan-interval

Nálam is sűrűbbre volt beállítva a frissítés és jött levél a Díjnet ügyfélszolgálattól, hogy látják, hogy folyamatosan pollozom a rendszerüket, állítsam le a scriptet ami ezt csinálja, mert ezzel "fölöslegesen" terhelem a szerverüket. Rákérdeztem, hogy a 3 óránkénti bejelentkezés rendben van-e és arra még azt mondták, hogy maradhat. Emiatt van a 3 órás érték. Űgyhogy kisebb frissítési időintervallumot nem javaslok beállítani, hiába adott rá a lehetőség.

**Comment by KixMan28** [comment]
> 
> 
> @KixMan28
> 
> > @laszlojakab Úgy tünik letelt a 3 óra, most újból látszik a szilgáltató szenzor.
> > Esetleg egy másik javaslat: legyen állítható a frissítési intervallum.
> > Egyébként nagyon szépen köszönöm az alkalmazást.
> 
> Egyelőre működik a scan_interval lehetőség:
> https://www.home-assistant.io/docs/configuration/platform_options/#scan-interval
> 
> Nálam is sűrűbbre volt beállítva a frissítés és jött levél a Díjnet ügyfélszolgálattól, hogy látják, hogy folyamatosan pollozom a rendszerüket, állítsam le a scriptet ami ezt csinálja, mert ezzel "fölöslegesen" terhelem a szerverüket. Rákérdeztem, hogy a 3 óránkénti bejelentkezés rendben van-e és arra még azt mondták, hogy maradhat. Emiatt van a 3 órás érték. Űgyhogy kisebb frissítési időintervallumot nem javaslok beállítani, hiába adott rá a lehetőség.

OK. Megértettem. Akkor ezen nem változtatnék. Ebben az esetben visszérnék az előbbi javaslatomhoz: a szolgáltató szenzor legyen mindig aktív, ha van számla és nincs befizetve akkor a számla összegét mutassa, ha nincs számla, vagy már befizetésre került, akkor mutasson 0 Ft-ot.

**Comment by KixMan28** [comment]
Köszi szépen. Egy kérdés: lehet 2 különböző Díjnet fiókot hozzáadni a Home Assistant-hoz és ha igen, hogyan?

**Comment by laszlojakab** [comment]
@KixMan28: ha még aktuális a kérdés 1.5 év után, most már elvileg hozzáadható több Dijnet-es fiók is HA-hoz a develop-ban lévő branch-ből (release-elve még nem lett, és az eddigi szenzorok teljesen át lettek alakítva, új névvel jönnek létre így, ha épült a régi Díjnetes integrációra valamilyen automatizálás/felület, akkor azt módosítani kell!)

**Comment by KixMan28** [comment]
@laszlojakab Köszi szépen az infót. Már régóta hozzáadtam egy második Díjnet fiókot és működik.

**Comment by spider7611** [comment]
Üdv! Szeretnék hozzáadni én is még egy regisztrációt. Letöltöttem HACS- on a develop -ot de nem tudok plusz regisztrációt hozzáadni. Megváltozott a szenzorok neve újraindítás után, de az integráció alatt nincs új reg hozzáadása funkció. Mit nézek el?
