### ISSUE TITLE
Platform dijnet does not generate unique IDs

### ISSUE THREAD

**Issue by Tompi89** [laszlojakab/homeassistant-dijnet#32]
Szia Laci!

Sajnos a dijnet integrációban megjelenik minden entitás, de az értéke nem változik. Tegnap készült a gázszámlám, de 0 Ft-ot ír a sensor, és látom a naplóban, hogy az alábbi hibaüzenetek jelennek meg:

`Platform dijnet does not generate unique IDs. ID 6e12260df9e56bf9cf43d8a917c2fa6e_Allianz_AHB936578XXX_Allianz_amount already exists - ignoring sensor.dijnet_allianz_tompi_e38
Platform dijnet does not generate unique IDs. ID 6e12260df9e56bf9cf43d8a917c2fa6e_ÉRV Zrt._670000196XXX_Allianz_amount already exists - ignoring sensor.dijnet_erv
Platform dijnet does not generate unique IDs. ID 6e12260df9e56bf9cf43d8a917c2fa6e_MVM Next - Földgáz_000033024807_Allianz_amount already exists - ignoring sensor.dijnet_mvm_foldgaz
Platform dijnet does not generate unique IDs. ID 6e12260df9e56bf9cf43d8a917c2fa6e_NHKV Zrt._00160131700000146680205_Allianz_amount already exists - ignoring sensor.dijnet_nhkv
Platform dijnet does not generate unique IDs. ID 6e12260df9e56bf9cf43d8a917c2fa6e_Telekom otthoni, Telekom-összevont_400093363_Allianz_amount already exists - ignoring sensor.dijnet_telekom`

Először csak Allianz elnevezésekkel jelentek meg az entitások, de valamiért nem működik így megfelelően. A telepítés óta csak Allianz volt fizetendő eddig, az működött hozzáadáskor ahogy kell. Tudsz esetleg segíteni, hogy mit rontok el?

Köszönöm! Üdv: Tompi

**Comment by laszlojakab** [comment]
Szia! @Tompi89 megoldódott a probléma?
