### ISSUE TITLE
Fizetendő számla összege nem jelenik meg.

### ISSUE THREAD

**Issue by sonycim** [laszlojakab/homeassistant-dijnet#34]
Üdvözletem!

Az integráció nem jeleníti meg a fizetendő számlák összegét.
Nem tudom, milyen időközönként kéri le az alkalmazás az adatokat, de a dijenttől 11:49-kor érkezett értesítés, az integrációban pedig még most sem jelent meg az összeg (15:20).

Illetve, ha jól rémlik, akkor az integráció egy korábbi fázisában volt egy olyan szenzor is, amely a nyitott tételek teljes összegét tartalmazta.
Ez miért került kivezetésre?
Azért volt hasznos, mert nem kellett külön-külön figyelni az egyes számlakibocsátókat, hanem ha az az érték nem nulla volt, akkor tudtam, hogy van befizetendőm.

![dijnet](https://user-images.githubusercontent.com/72749518/153608973-76d4b671-e0c0-44dd-93d4-6fd1a065057e.JPG)

**Comment by laszlojakab** [comment]
Szia @sonycim, 

A szenzorok frissítése 3 óránként történik, így legrosszabb esetben is 14:50-kor már meg kellett volna jelennie az összegnek. Lenne néhány kérdésem: 

- melyik verzióját használod az integrációnak?
- a naplóban van bármilyen hiba a Dijnettes integrációval kapcsolatban? 
- ha nincs hiba, akkor HA újraindítás után sem jelenik az összeg?
- be tudnád kapcsolni a naplózást configuration.yaml-be (a critical szintet azért írtam bele, hogy csak a Dijnetes integrációval kapcsolatos infók jelenjenek meg, ha szükséged van a többi integráció logjára, akkor ez a szintet lehet átírni mondjuk `error`, vagy `warning`, vagy `info`, esetleg `debug` szintre, nyilván ilyenkor nehezebb lesz áttekinteni a naplót, hogy mi tartozik a dijnetes integrációhoz:

```yaml
logger:
  default: critical
  logs:
    custom_components.dijnet: debug
```
 - amennyiben újraindítás után nem jelentkezik a hiba, akkor megköszönném, ha benne tudnád hagyni a naplózást a config-odban és ha legközelebb újra előjön a hiba, akkor átküldenéd nekem a naplóból a részleteket.

A teljes fizetendő összeg szenzort más is kérdezte, itt kifejtettem, hogy miért nem került került ki (illetve miért nem került be az új verzióba): https://github.com/laszlojakab/homeassistant-dijnet/issues/30#issuecomment-1024734209
Még annyit tennék hozzá, hogy valószínűleg neked valójában nem is arra lenne szükséged, hogy mennyi az aktuálisan fizetendő összeg, hanem arra, hogy van-e egyáltalán fizetni való? Ebben az esetben egy binary template szenzort javasolnék, amelyben a következő értéket adod meg:

```yaml
{% set ns = namespace(sum=0) %}
{% for entity in integration_entities('dijnet') %}
{% set ns.sum = ns.sum + float(states(entity), 0) %}
{% endfor %}
{{ ns.sum > 0 }}
```

Ha feltétlen szükség van az aktuálisan fizetendő összegre, akkor leveszed a `> 0`-t és normál template sensor-t hozol létre, így visszakapod az régi "teljes összeges" szenzor értékét.

**Comment by sonycim** [comment]
Integráció: 0.5.0
Átírtam a logger szekciót, az általad javasoltra.
Hiba szerintem jelent meg.
Ellenben újraindítás után sem jelenik meg az összeg.

Így van. Csak annyit szeretnék tudni, hogy van-e befizetendőm.
Ez a template dolog nekem nagy mumus.
Még soha nem tudtam összehozni.
Leírnál egy olyan verziót, ahol
-platform: - tól kezdve van? :)
Illetve azt, hogy ez pontosan melyik yaml-ba kell tenni?
Nekem a sensors lenne a logikus.
![dijnet_1](https://user-images.githubusercontent.com/72749518/153815105-d025f3ec-b85f-42d6-b7be-fe6f0ece4bb9.PNG)
![dijnet_2](https://user-images.githubusercontent.com/72749518/153815107-d36fa1be-88fa-45e3-b859-38c174751dce.PNG)
![dijnet_3](https://user-images.githubusercontent.com/72749518/153815109-62c80e4e-daf9-48f7-9c95-d5b0c86a3870.jpg)

**Comment by laszlojakab** [comment]
Hibakereséshez a naplóból a "teljes"-re lenne szükség, nem csak erre a néhány sorra. Ezt a `home-assistant.log` fileból kellene kimásolni. Illetve, ha nem férsz hozzá, akkor a másik lehetőség a _Konfiguráció_ menüpont alatt a _Napló_ fül választása, majd az alján találsz egy _Teljes Home Assistant napló betöltése_ gombot, arra kellene kattintani és az ott megjelent szöveget ide bemásolni.

A számlakibocsátói oszlopban a kisatírozott részen, nincsen véletlen valamilyen ékezetes/speciális karakter? Esetleg nem csoportos beszedésű a számla (ez az utolsó oszlopból derülne ki ami nincs a képen)?

Template binary sensor-t így tudod összerakni (platform nem kell):

```yaml
template:
  - binary_sensor:
      - name: Van fizetendő számla
        state: >- 
          {% set ns = namespace(sum=0) %}
          {% for entity in integration_entities('dijnet') %}
          {% if entity.startswith("sensor.dijnet_") %}
          {% set ns.sum = ns.sum + float(states(entity), 0) %}
          {% endif%}
          {% endfor %}
          {{ ns.sum > 0 }}
        icon: mdi:cash

```

**Comment by sonycim** [comment]
Köszönöm, a template dolgot!
Tökéletes.

Mellékeltem a számla soráról készült képet.
Ez csak sima e-számla.
Csatoltam a logot is.

[HA_dijnet_log.txt](https://github.com/laszlojakab/homeassistant-dijnet/files/8081021/HA_dijnet_log.txt)
![dijnet_1](https://user-images.githubusercontent.com/72749518/154295166-517255cc-11a4-4705-a373-deb3e160edf3.PNG)

**Comment by sonycim** [comment]
Nem jelent meg.
Ellenben valaminő hiba már látszik a logban:
2022-02-17 00:28:44 DEBUG (MainThread) [custom_components.dijnet.controller] ".dijnet_paid_invoices.yaml" or ".dijnet_registry.yaml" not found.

[dijnet_0217.txt](https://github.com/laszlojakab/homeassistant-dijnet/files/8084327/dijnet_0217.txt)

**Comment by laszlojakab** [comment]
Még egy dolgot próbáljunk ki kérlek a logger-nek a `default` szintjét állítsd át error-ra:

```yaml
logger:
  default: error
  logs:
    custom_components.dijnet: debug
```

Utána nézzük meg kerül-e be valami a naplóba.

**Comment by sonycim** [comment]
Nos.
Az alábbi hiba generálódott:
Egyébként most nem az NHKV-nál van fizetendőm, de legutóbb az sem jelent meg.


> Ez a hiba egy egyéni integrációból lett származtatva.

Logger: homeassistant.helpers.entity
Source: custom_components/dijnet/controller.py:453
Integration: Dijnet (documentation, issues)
First occurred: 21:30:35 (1 occurrences)
Last logged: 21:30:35

Update for sensor.dijnet_nhkv_zrt_fizetendo_osszeg fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 733, in async_device_update
    await task
  File "/config/custom_components/dijnet/sensor.py", line 121, in async_update
    invoices = [invoice for invoice in await self._controller.get_unpaid_invoices() if invoice.display_name == self._invoice_issuer.display_name and invoice.provider == self._provider]
  File "/config/custom_components/dijnet/controller.py", line 332, in get_unpaid_invoices
    await self.update_invoices()
  File "/config/custom_components/dijnet/controller.py", line 453, in update_invoices
    directory = path.join(self._download_dir, slugify(invoice.provider))
AttributeError: 'NoneType' object has no attribute 'provider'

**Comment by laszlojakab** [comment]
A szenzorok adatai "egyszerre" számolódnak ki, csak egyszer megy el az integráció a Dijnet oldalára és tölt le mindent. Utána a szenzorok a letöltött adatokból "válogatják ki" azokat az információkat amik számukra relevánsak. Emiatt, ha az NHKV-s adatok betöltése elhasal, az befolyásolhatja a további adatok betöltését, tehát más szenzorok sem fognak értéket kapni. Tehát itt alapvetően valószínűleg csak az NHKV-s adatok betöltésénél van a gond, nem a Telekomosnál (ez már csak következmény, hogy itt nincs fizetendő összeg). Átnézem a kódot, hogy látok-e valamit ami okozhatja a fent írt hibát és visszajelzek a továbbiakról.

**Comment by laszlojakab** [comment]
A számlakeresés menüpontban, ha kiválasztod a szolgáltatónál az NHKV-t, rányomsz a keresésre, akkor elvileg kellene látnod _Rendezett_ állapotú NHKV-s számlákat. A kérdés az, hogy találsz-e olyat, amire rákattintva az _Események_ fülön a képen látható táblázat üres/nem létezik vagy valahogy "rendellenesen" néz ki?

![image](https://user-images.githubusercontent.com/6196882/154646488-15fe410a-9fbf-488e-b47e-02f82514c059.png)

**Comment by sonycim** [comment]
Öhm...
Semmi változás.
Azt hiszem, az előző is ezzel a hibakóddal végződött:
"AttributeError: 'NoneType' object has no attribute 'provider'_"
Nem tudnék küldeni valami olyan adatot, amiből kiderülne, hogy a hiba nálam, a weblapon, vagy hol lehet?

```
Ez a hiba egy egyéni integrációból lett származtatva.

Logger: homeassistant.helpers.entity
Source: custom_components/dijnet/controller.py:457
Integration: Dijnet (documentation, issues)
First occurred: 20:57:42 (1 occurrences)
Last logged: 20:57:42

_Update for sensor.dijnet_nhkv_zrt_fizetendo_osszeg fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 733, in async_device_update
    await task
  File "/config/custom_components/dijnet/sensor.py", line 121, in async_update
    invoices = [invoice for invoice in await self._controller.get_unpaid_invoices() if invoice.display_name == self._invoice_issuer.display_name and invoice.provider == self._provider]
  File "/config/custom_components/dijnet/controller.py", line 332, in get_unpaid_invoices
    await self.update_invoices()
  File "/config/custom_components/dijnet/controller.py", line 457, in update_invoices
    directory = path.join(self._download_dir, slugify(invoice.provider))
AttributeError: 'NoneType' object has no attribute 'provider'_
```

**Comment by laszlojakab** [comment]
Ahogyan írtam a hibát ez nem oldja meg csak a naplózást bővítette. Kérlek az egész naplót csatold, abban elvileg benne lesz, hogy mit töltött le a Díjnet oldaláról.

**Comment by sonycim** [comment]
Mindössze ennyi történt azóta:
```

Ez a hiba egy egyéni integrációból lett származtatva.

Logger: custom_components.dijnet.controller
Source: custom_components/dijnet/controller.py:450
Integration: Dijnet (documentation, issues)
First occurred: 20:57:42 (1 occurrences)
Last logged: 20:57:42

History row not found
```

**Comment by laszlojakab** [comment]
A `History row not found` után kellene lennie egy debug szintű üzenetnek, ezt a felületen szerintem nem lehet látni, át tudod küldeni a napló filet?

**Comment by sonycim** [comment]
Van benne egy rakat más cucc is.
Jó böngészést!


[home-assistant.log](https://github.com/laszlojakab/homeassistant-dijnet/files/8100222/home-assistant.log)

**Comment by laszlojakab** [comment]
A rakás más cucc nem gond (a napló fileok általában ilyenek, ez még bőven kicsinek számít amúgy), így már látszik mi akasztotta ki az integrációt. Van egy 2016-os számlád Tigáztól (2016.10.05), amin valamiért másképp jelennek meg a felületen a dolgok, mint a többi számlán: itt a táblázat amit fentebb említettem üres (sőt a neve is más, mint a normál esetben, ez kódból látszik). Az téves feltételezés volt, hogy az NHKV-től van a számla amivel a problémva van, csak az NHVK-s szenzor volt ami elindította az adatok betöltését, emiatt tűnt úgy, hogy ezzel van gond. Tehát ez a Tigázos számla borítja meg utána minden más számla letöltését. Ma már nem, de kitalálok rá hamarosan valamit és akkor kiadok egy új verziót neked tesztelésre.

**Comment by laszlojakab** [comment]
Újra tudnád telepíteni innen az integrációt és megnézni, hogy most már megjelennek-e az összegek? https://github.com/laszlojakab/homeassistant-dijnet/tree/fix/sonycim
Köszönöm!

**Comment by sonycim** [comment]
Megtörtént.
A Telekomos összeg nem jelent meg.
Ha jól látom, akkor a vodás számlákban a hiba.
Azt egyébként miért csinálja a program, hogy a világ végéig lekér minden számlát?
Lényegében 3, de nagyon maximum 4 hónap után úgyis lelövik a szolgáltatást.
Ergo bármennyi be nem fizetett számla is volt tavaly, az már lejárt tartozás.
Teljesen felesleges listázni.

[sonycim_log.txt](https://github.com/laszlojakab/homeassistant-dijnet/files/8103047/sonycim_log.txt)

**Comment by laszlojakab** [comment]
Egyelőre a napló alapján nekem nem tűnik rossznak (vannak benne olyan számlák, amiknek a befizetés dátumát most sem találta meg, de tovább ment - ilyenkor a fizetési határidőt írtam most bele befizetés dátumának, ha a számla fizetve állapotban van), csak szerintem még nem történt meg az első adatletöltés (ez eltarthat hosszabb ideig, főleg hogy bekapcsoltad a számlák letöltését is).

A _világ végéig_ azért kéri le, hogy egy még ki nem adott új funkció tudjon majd működni (illetve, hogy a számla pdf-eket le tudja tölteni): a HA-ban lehetőség van naptárakat használni, a terv az, hogy a naptárba is be tud majd épülni a Díjnetes integráció. Ehhez viszont, hogy használható legyen régebbi dátumokra is meg kell, hogy legyenek az adatok. Egyébként a _világ végéig_ csak 1x tölt le mindent, utána letárolja a letöltött adatokat és a következő betöltéskor már csak egy kis időszakot néz. Emiatt nem _teljesen felesleges a listázás_.

Azóta sem töltődött be, illetve nem kerültek be még további napló bejegyzések?

**Comment by sonycim** [comment]
Hehh! :)
Siker! :)))
Szuper!

**Comment by laszlojakab** [comment]
Kiadásra vár egy verzió, ami csak leghamarabb jövőhónap elején fog kimenni (tesztelés alatt van valakinél, le kell, hogy járjon egy számla), valamikor utána fogok tudni csak kiadni egy olyan verziót ami a Te problémádat fogja megoldani véglegesen. Addig is használd azt a verziót amit utoljára adtam.

**Comment by laszlojakab** [comment]
@sonycim kiadásra került a 0.5.2-beta verzió, ebben már benne van a javítás, amit korábban kézzel telepítettél.
