### ISSUE TITLE
install -> async_install

### ISSUE THREAD

**Issue by kevegabi** [laszlojakab/homeassistant-dijnet#4]
Szia László!

Az alábbi warning -ot dobta a frissítést követően a HA:

Log Details (WARNING)
Logger: hacs.repository.integration.laszlojakab.homeassistant-dijnet
Source: custom_components/hacs/repositories/helpers/methods/installation.py:17
First occurred: 7:15:19 PM (1 occurrences)
Last logged: 7:15:19 PM

'install' is deprecated, use 'async_install' instead

Hibát nem okozott, szépen települt az új verzió. ;)

Rendszer: 
Home Assistant Core 0.111.0
HassOS 4.10
Supervisor: 227

Szép napot,
kga

**Comment by laszlojakab** [comment]
Úgy látom HACS-ban van a probléma, nem a Díjnetes integrációban: hacs/integration#1320
