### ISSUE TITLE
Fizetendő számlák összesen entitás hiánya

### ISSUE THREAD

**Issue by szivosp** [laszlojakab/homeassistant-dijnet#45]
Szia.
Az előző verziókban volt fizetendő számlák összesen entitás. Nekem rettenetesen hiányzik! Nem lehetne visszatenni valamelyik frissítésben?

**Comment by laszlojakab** [comment]
Szia!

Nem tervezem visszarakni, bővebben itt írtam róla, hogy miért: https://github.com/laszlojakab/homeassistant-dijnet/issues/30#issuecomment-1024734209

Ha a commentemet elolvasod és utána tudsz meggyőző érvet mondani, hogy miért van rá mégis szükség, hogy az integráció része legyen egy ilyen szenzor, akkor viszont beszélhetünk róla.

Egyébként, ha nem kerülne vissza és neked ettől függetlenül mindenképp szükséged van rá, akkor is megoldható, hogy lásd a teljes fizetendő összeg aktuális értékét egy template szenzor segítségével:

```yaml
template:
  - sensor:
      - name: Fizetendő számlák összege
        state: >- 
          {% set ns = namespace(sum=0) %}
          {% for entity in integration_entities('dijnet') %}
          {% if entity.startswith("sensor.dijnet_") %}
          {% set ns.sum = ns.sum + float(states(entity), 0) %}
          {% endif%}
          {% endfor %}
          {{ ns.sum }}
        icon: mdi:cash
```

Vagy, ha csak az érdekel, hogy van-e bármilyen fizetendő számlád, akkor elgendő egy binary senor:

```yaml
template:
  - binary_sensor:
      - name: Van fizetendő számla
        state: >- 
          {% set ns = namespace(sum=0) %}
          {% for entity in integration_entities('dijnet') %}
          {% if entity.startswith("sensor.dijnet_") %}
          {% set ns.sum = ns.sum + float(states(entity), 0) %}
          {% endif%}
          {% endfor %}
          {{ ns.sum > 0 }}
        icon: mdi:cash
```

**Comment by szivosp** [comment]
Szia! Az egyetlen épkézláb érvem szertefoszlott a kapott információk alapján. Az összesen értéket kirakom sensor-ral és megpróbálom a belinkelt kártyát is. Köszönöm a segítséget!
