### ISSUE TITLE
fix: not supported state `Mobiltelefonra küldve`

### ISSUE THREAD

**Issue by spider7611** [laszlojakab/homeassistant-dijnet#52]
Üdv!

Hajnalban megjött az email, de HA azóta sem jelzett hogy fizetendő számlám lenne. 
Mi lehet a gond?
![kuka](https://user-images.githubusercontent.com/45290475/164916092-db576202-b7cb-4430-a013-7876cc950d2b.jpg)
![kuka2](https://user-images.githubusercontent.com/45290475/164916095-99489f7a-6ada-44cf-9b28-6a9a861beca8.jpg)

Köszönöm.

**Comment by spider7611** [comment]
Naplóba ezt találtam:
![naplo](https://user-images.githubusercontent.com/45290475/164916227-946a88f9-d89f-4a2e-a430-173374f9e47b.jpg)

**Comment by laszlojakab** [comment]
Szia, köszönöm a bejelentést. Arról tudsz nekem mondani valamit, hogy mi lehet ez az állapot, hogy  `Mobiltelefonra küldve`? Milyen módon fizeted ezt a számlát?

**Comment by spider7611** [comment]
Üdv! Fogalmam nincs hogy miért van az odaírva. Még ebből egyet sem fizettem mert az utolsó számla után regisztráltam és ez az első számla ami itt érkezett.

**Comment by laszlojakab** [comment]
Innen fel tudnád telepíteni az integrációt és megnézni működik-e? https://github.com/laszlojakab/homeassistant-dijnet/tree/fix/add-support-for-icsekk

Illetve, ha működik azt is szeretném kérni, hogy jelezz vissza, hogy befizetés után rendesen megjelenik-e HA-ban, hogy befizetted. Köszönöm!

**Comment by spider7611** [comment]
Rajta vagyok a dolgon, de egyenlőre nem indul el a HACS integrációm, Egy vasárnapi mentés visszatétele után nem hajlandó elindulni a HACS. :( Jelentkezem amint megoldottam valahogy a dolgot.

**Comment by spider7611** [comment]
Megtörtént a telepítés és megjelent az összeg! Fizetni később fogom, de majd jelzem. ;)

**Comment by spider7611** [comment]
Kifizettem hamarabb hogy lássuk mi történik. Az összeg lenullázódott fizetés után kb 3 órával a HA-ban. Szóval működik!
Jöhet a frissítés. ;)
Köszönjük a munkád.

**Comment by laszlojakab** [comment]
0.5.5-ben kiadva.
>Köszönjük a munkád.

Szivesen :)
