### ISSUE TITLE
Telepítési hiba

### ISSUE THREAD

**Issue by Pulpi86** [laszlojakab/homeassistant-dijnet#55]
Szia megpróbáltam felrakni ezt az integrációt de ezt a hibaüzenetet kaptam:
"This integration does not support via the UI. If you followed this link from home asssistant website, make sure you run latest version of Home Assitant."

Van erre valami megoldás? 
HA verzió: core-2022.6.5
Köszi

**Comment by laszlojakab** [comment]
Szia! Még nem találkoztam a problémával, de nálam egyelőre csak 2022.5-ös HA van, felrakom 2022.6-ost és megnézem.

**Comment by laszlojakab** [comment]
@Pulpi86 felraktam 2022.6-ot és gond nélkül feltelepült az integráció. Napló fileban van esetleg hibaüzenet? Illetve HACS-ből telepítetted, vagy felmásoltad a mappát a custom_components mappába?

**Comment by Pulpi86** [comment]
@laszlojakab HACSból telepíteném, de hibára fut. Logban nincs semmi hiba. A manuális telepítést még nem próbáltam, azt majd megpróbálom. Ez a hibaüzenet:
![HA_dijnet_error](https://user-images.githubusercontent.com/83541304/173999641-a312f21d-b890-4a76-a0f6-1526b890d297.jpg)
.

**Comment by Pulpi86** [comment]
Működik! A manuális telepítési móddal működik. 

Köszönöm a segítséget. A fizetési hatéridőket is meg  tudja jeleníteni?
