### ISSUE TITLE
Failed to determine invoice state. State column text: Internetbanknak átadva

### ISSUE THREAD

**Issue by naszydeny** [laszlojakab/homeassistant-dijnet#57]
Szia,

Kaptam számlákat a Dijnet-be, viszont nem jeleníti meg a fizetendő tételeket és a naplóban ez a hibaüzenet jelenik meg:
**_Logger: custom_components.dijnet.controller
Source: custom_components/dijnet/controller.py:468
Integration: Dijnet ([documentation](https://github.com/laszlojakab/homeassistant-dijnet#usage), [issues](https://github.com/laszlojakab/homeassistant-dijnet/issues))
First occurred: 15:20:52 (2 occurrences)
Last logged: 15:20:53

Failed to determine invoice state. State column text: Internetbanknak átadva_**

A számlákat beküldetem az internetbankba és onnan fizetem (CIB), ami azt jelenti, hogy amint bekerül a Dijnet rendszerében, beküldi az internetbankba, ahonnan egyszerűen tudom fizetni és egészen addig ebben a státuszban marad, amíg ki nem fizetem és akkor kerül át rendezett státuszban. Ez egy nem kifizetett számlának minősül ilyenkor.

Köszi.
Üdv.:
Dani

**Comment by laszlojakab** [comment]
Szia Dani,

Köszi a bejelentést. Ki tudnád próbálni ezzel a verzióval működik-e: https://github.com/laszlojakab/homeassistant-dijnet/tree/feat/add-support-for-internet-banking ?

Üdv,
Laci

**Comment by naszydeny** [comment]
Szia Laci,
Működik, íygy már megjelentek a számlák. Köszi.
Üdv.:
Dani

**Comment by laszlojakab** [comment]
Szia Dani,
A módosítás kiadásra került a 0.5.6-os verizóban.
Üdv,
Laci
