### ISSUE TITLE
No sensors showing up after 2022-11-18

### ISSUE THREAD

**Issue by tszaniszlo** [laszlojakab/homeassistant-dijnet#64]
Hi, 

Trying to enable dijnet sensor in my environment, for some reason nothing is showing up. No new sensor is visible, sensors should be available not found. In the log I find that sensors are successfuly set up but no sensor found.

Thanks,
tamás

**Comment by laszlojakab** [comment]
Related to #63.

**Comment by laszlojakab** [comment]
@tszaniszlo could you please try this version: https://github.com/laszlojakab/homeassistant-dijnet/tree/fix/modify-parsing-according-to-2022-11-18 ?

**Comment by KixMan28** [comment]
It works again with the latest modifications you made yesterday. I have copied the content of the two modified files to my instance, I restarted HA and after restart everything shows up as expected. Thank you for the quick fix.

**Comment by tszaniszlo** [comment]
Thanks, it is fixed now
