### ISSUE TITLE
nem tölti le a számlákat

### ISSUE THREAD

**Issue by hellboyhu** [laszlojakab/homeassistant-dijnet#72]
Helló!

Nem rég vettem észre, hogy 2022. novemberben töltött le utoljára számlákat.
Más is mondta, hogy találkozott ezzel a hibával. Ki probáltam régebbi verzióval, de azzal sem. 
Lehetne segítséget kérni hogy merre lehetne elindulni?

Köszönöm!

**Comment by laszlojakab** [comment]
Szia! Készítettem egy javítást, ki tudnád próbálni ezzel a verzióval?

https://github.com/laszlojakab/homeassistant-dijnet/tree/fix/update-css-selector-for-invoice-downloading

**Comment by hellboyhu** [comment]
Szia!

Kiprobáltam, és az utolsó hónapot le töltötte. Régebieket nem. de azok megvannak. Ha továbra is letölti, akkor tökéletes lesz. 
Köszönöm a gyors segítséget, javítást! :)

**Comment by laszlojakab** [comment]
0.6.2-es verzióban kiadva.
